---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery' 
summary: Scopri le modifiche più recenti apportate ai servizi cloud che fanno parte della piattaforma BlueXP. 
---
= Recenti cambiamenti in BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti apportate ai servizi cloud che fanno parte della piattaforma BlueXP. Per una cronologia completa delle versioni, andare al link:release-notes-index.html["set completo di note di rilascio"] per ogni singolo servizio.



== Funzionalità amministrative

In questa sezione vengono descritte le nuove funzionalità relative alle funzioni di amministrazione di BlueXP: Account, connettori, credenziali del provider cloud e altro ancora.



=== 21 luglio 2025



==== Supporto per Google Cloud NetApp Volumes

Ora puoi visualizzare Google Cloud NetApp Volumes in BlueXP. link:https://docs.netapp.com/us-en//bluexp-google-cloud-netapp-volumes/index.html/index.html["Scopri di più su Google Cloud NetApp Volumes."]



==== Gestione delle identità e degli accessi (IAM, Identity and Access Management) di BlueXP



===== Nuovo ruolo di accesso per Google Cloud NetApp Volumes

BlueXP ora supporta l'utilizzo di un ruolo di accesso per il seguente sistema di archiviazione:

* Google Cloud NetApp Volumes


link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Scopri di più sull'utilizzo dei ruoli di accesso."]



=== 14 luglio 2025



==== Connettore 3.9.54

Questa versione di BlueXP Connector include miglioramenti della sicurezza, correzioni di bug e le seguenti nuove funzionalità:

* Supporto per proxy trasparenti per i connettori dedicati al supporto dei servizi Cloud Volumes ONTAP . link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Scopri di più sulla configurazione di un proxy trasparente."]
* Possibilità di utilizzare tag di rete per agevolare l'instradamento del traffico del connettore quando il connettore viene distribuito in un ambiente Google Cloud.
* Notifiche aggiuntive nel prodotto per il monitoraggio dello stato del connettore, incluso l'utilizzo di CPU e RAM.


Al momento, la versione 3.9.54 è disponibile per la modalità standard e la modalità limitata.



==== Gestione delle identità e degli accessi (IAM, Identity and Access Management) di BlueXP

La gestione delle identità e degli accessi in BlueXP offre ora le seguenti funzionalità:

* Supporto per IAM in modalità privata, che consente di gestire l'accesso utente e le autorizzazioni per i servizi e le applicazioni BlueXP .
* Gestione semplificata delle federazioni di identità, con navigazione più semplice, opzioni più chiare per la configurazione delle connessioni federate e maggiore visibilità sulle federazioni esistenti.
* Ruoli di accesso per il BlueXP backup and recovery, il BlueXP disaster recovery e la gestione della federazione.




===== Supporto per IAM in modalità privata

BlueXP ora supporta l'IAM in modalità privata, consentendo di gestire l'accesso e le autorizzazioni degli utenti per i servizi e le applicazioni BlueXP . Questo miglioramento consente ai clienti in modalità privata di sfruttare il controllo degli accessi basato sui ruoli (RBAC) per una maggiore sicurezza e conformità.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#iam["Scopri di più su IAM in BlueXP."]



===== Gestione semplificata delle federazioni di identità

BlueXP offre ora un'interfaccia più intuitiva per la gestione della federazione delle identità. Ciò include una navigazione più semplice, opzioni più chiare per la configurazione delle connessioni federate e una migliore visibilità sulle federazioni esistenti.

Abilitando il Single Sign-On (SSO) tramite la federazione delle identità, gli utenti possono accedere a BlueXP con le proprie credenziali aziendali. Questo migliora la sicurezza, riduce l'uso delle password e semplifica l'onboarding.

Ti verrà richiesto di importare eventuali connessioni federate esistenti nella nuova interfaccia per accedere alle nuove funzionalità di gestione. Questo ti permetterà di sfruttare i più recenti miglioramenti senza dover ricreare le tue connessioni federate. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-federation-import.html["Scopri di più sull'importazione della tua connessione federata esistente in BlueXP."]

Una gestione migliorata della federazione consente di:

* Aggiungi più di un dominio verificato a una connessione federata, consentendoti di utilizzare più domini con lo stesso provider di identità (IdP).
* Disattiva o elimina le connessioni federate quando necessario, per avere il controllo sull'accesso degli utenti e sulla sicurezza.
* Controlla l'accesso alla gestione della federazione con i ruoli IAM.


link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-federation.html["Scopri di più sulla federazione delle identità in BlueXP."]



===== Nuovi ruoli di accesso per il BlueXP backup and recovery, il BlueXP disaster recovery e la gestione della federazione

BlueXP ora supporta l'utilizzo dei ruoli IAM per le seguenti funzionalità e servizi dati:

* Backup e ripristino BlueXP
* Disaster recovery di BlueXP
* Federazione


link:https://docs.netapp.com/us-en/bluexp-admin/reference-iam-predefined-roles.html["Scopri di più sull'utilizzo dei ruoli di accesso."]



=== 9 giugno 2025



==== Connettore 3.9.53

Questa versione di BlueXP Connector include miglioramenti della sicurezza e correzioni di bug.

La versione 3.9.53 è disponibile per la modalità standard e la modalità limitata.



==== Avvisi sull'utilizzo dello spazio su disco

Il Centro notifiche ora include avvisi sull'utilizzo dello spazio su disco sul Connettore. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#monitor-disk-space["Scopri di più."^]



==== Miglioramenti dell'audit

La cronologia ora include gli eventi di accesso e disconnessione degli utenti. È possibile visualizzare l'attività di accesso, utile per il controllo e il monitoraggio della sicurezza. Gli utenti API con il ruolo di amministratore dell'organizzazione possono visualizzare l'indirizzo email dell'utente che ha effettuato l'accesso includendo  `includeUserData=true`` parametro come nel seguente:  `/audit/<account_id>?includeUserData=true` .



==== Gestione degli abbonamenti Keystone disponibile in BlueXP

Puoi gestire il tuo abbonamento NetApp Keystone da BlueXP.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["Scopri di più sulla gestione degli abbonamenti Keystone in BlueXP."^]



==== Gestione delle identità e degli accessi (IAM, Identity and Access Management) di BlueXP



===== Autenticazione a più fattori (MFA)

Gli utenti non federati possono abilitare l'MFA per i propri account BlueXP per migliorare la sicurezza. Gli amministratori possono gestire le impostazioni dell'MFA, inclusa la reimpostazione o la disattivazione dell'MFA per gli utenti, se necessario. Questa funzionalità è supportata solo in modalità standard.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa["Scopri come configurare autonomamente l'autenticazione a più fattori."^] link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#manage-mfa["Scopri come gestire l'autenticazione a più fattori per gli utenti."^]



==== Carichi di lavoro

Ora puoi visualizzare ed eliminare le credenziali Amazon FSx for NetApp ONTAP dalla pagina Credenziali in BlueXP.



=== 29 maggio 2025



==== Rilascio in modalità privata (3,9.52)

È ora disponibile una nuova versione in modalità privata da scaricare da https://mysupport.netapp.com/site/downloads["Sito di supporto NetApp"^]

La versione 3.9.52 include aggiornamenti ai seguenti componenti e servizi BlueXP.

[cols="3*"]
|===
| Componente o servizio | Versione inclusa in questa release | Cambia dalla precedente versione in modalità privata 


| Connettore | 3.9.52, 3.9.51 | Vai al  https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["Novità della pagina BlueXP  Connector"] e fare riferimento alle modifiche incluse nelle versioni 3.9.52 e 3.9.50. 


| Backup e recovery | 12 maggio 2025 | Vai al  https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["Novità della pagina di backup e ripristino di BlueXP"^] e fare riferimento alle modifiche incluse nella versione di maggio 2025. 


| Classificazione | 12 maggio 2025 (versione 1.43) | Andare a https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["Novità della pagina di classificazione BlueXP"^] e fare riferimento alle modifiche incluse nelle versioni da 1,38 a 1.371.41. 
|===
Per ulteriori informazioni sulla modalità privata, inclusa la modalità di aggiornamento, fare riferimento a quanto segue:

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Informazioni sulla modalità privata"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Scopri come iniziare a utilizzare BlueXP in modalità privata"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["Informazioni su come aggiornare il connettore quando si utilizza la modalità privata"]




== Avvisi



=== 7 ottobre 2024



==== Pagina dell'elenco degli avvisi BlueXP

Puoi identificare rapidamente i cluster ONTAP con bassa capacità o performance ridotte, valutare il grado di disponibilità e identificare i rischi per la sicurezza. Puoi visualizzare avvisi relativi a capacità, performance, protezione, disponibilità, sicurezza e configurazione.



==== Dettagli avvisi

Puoi approfondire i dettagli degli avvisi e trovare consigli.



==== Visualizza i dettagli del cluster collegati a Gestore di sistema di ONTAP

Gli alert BlueXP  ti consentono di visualizzare gli alert associati all'ambiente storage ONTAP e di analizzare nei dettagli collegati a ONTAP System Manager.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["Ulteriori informazioni sugli avvisi BlueXP"].



== Amazon FSX per ONTAP



=== 14 luglio 2025



==== Supporto per la replica dei dati tra due file system FSx per ONTAP

La replica dei dati è ora disponibile tra due file system FSx per ONTAP dalla console BlueXP.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#replicate-data["Replicare i dati"]



=== 29 giugno 2025



==== Aggiornamento delle credenziali

Dopo aver impostato credenziali e autorizzazioni per il file system FSx for ONTAP, verrai reindirizzato alla pagina Credenziali BlueXP. Da questa pagina puoi rinominare o rimuovere le tue credenziali FSx for ONTAP.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html["Impostare le autorizzazioni per FSx per i file system ONTAP"]



=== 04 maggio 2025



==== Supporto risposta Tracker

Tracker ora fornisce le risposte API in modo da poter vedere l'output dell'API REST relativo all'attività.



==== Supporto di autenticazione link per AWS Secrets Manager

Ora puoi utilizzare i segreti di AWS Secrets Manager per autenticare i link in modo da non dover utilizzare le credenziali archiviate nei workload di BlueXP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Connettersi a un file system FSX per ONTAP con un collegamento Lambda"]



==== Implementare le Best practice per un file system FSX per ONTAP

I carichi di lavoro BlueXP  fornisce una dashboard in cui puoi esaminare lo stato con l'architettura ideale delle configurazioni del file system. Puoi sfruttare questa analisi per implementare le Best practice per i file system FSX per ONTAP. L'analisi della configurazione del file system include le seguenti configurazioni: Soglia di capacità SSD, snapshot locali pianificate, backup FSX for ONTAP pianificati, tiering dei dati e replica dei dati remota.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Scopri l'analisi con un'architettura ideale per le configurazioni del file system"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["Implementare le Best practice per i file system"]




==== Notifica con un'architettura ottimale per i problemi del file system

Nella console BlueXP , i file system FSX per ONTAP con problemi ben strutturati ora visualizzano una notifica in Canvas che indica quando i file system hanno problemi da risolvere.



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



== Storage Amazon S3



=== 5 marzo 2023



==== Possibilità di aggiungere nuovi bucket da BlueXP

Hai avuto la possibilità di visualizzare i bucket Amazon S3 su BlueXP Canvas per un po' di tempo. Ora è possibile aggiungere nuovi bucket e modificare le proprietà per i bucket esistenti direttamente da BlueXP . https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["Scopri come aggiungere nuovi bucket Amazon S3"].



== Storage Azure Blob



=== 5 giugno 2023



==== Possibilità di aggiungere nuovi account storage da BlueXP

Hai avuto la possibilità di visualizzare Azure Blob Storage su BlueXP Canvas per un bel po' di tempo. A questo punto è possibile aggiungere nuovi account di archiviazione e modificare le proprietà degli account di archiviazione esistenti direttamente da BlueXP . https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["Scopri come aggiungere nuovi account di storage Azure Blob"].



== Azure NetApp Files



=== 13 gennaio 2025



==== Funzioni di rete ora supportate in BlueXP

Quando si configura un volume in Azure NetApp Files da BlueXP , è ora possibile indicare le funzioni di rete. Ciò si allinea con le funzionalità disponibili in Azure NetApp Files nativo.



=== 12 giugno 2024



==== È richiesta una nuova autorizzazione

Per gestire Azure NetApp Files Volumes da BlueXP è necessaria la seguente autorizzazione:

Microsoft.Network/virtualNetworks/subnets/read

Questa autorizzazione è necessaria per leggere una subnet di rete virtuale.

Se attualmente gestisci Azure NetApp Files da BlueXP, devi aggiungere questa autorizzazione al ruolo personalizzato associato all'applicazione Microsoft Entra precedentemente creata.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Informazioni su come configurare un'applicazione Microsoft Entra e visualizzare le autorizzazioni di ruolo personalizzate"].



=== 22 aprile 2024



==== I modelli di volume non sono più supportati

Non è più possibile creare un volume da un modello. Questa azione è stata associata al servizio di correzione BlueXP, che non è più disponibile.



== Backup e recovery



=== 28 luglio 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



==== Supporto del carico di lavoro Kubernetes in anteprima

Questa versione di BlueXP backup and recovery introduce il supporto per l'individuazione e la gestione dei carichi di lavoro Kubernetes:

* Scopri i cluster Red Hat OpenShift e Kubernetes open source, supportati da NetApp ONTAP, senza condividere i file kubeconfig.
* Scopri, gestisci e proteggi le applicazioni su più cluster Kubernetes utilizzando un piano di controllo unificato.
* Trasferisci le operazioni di spostamento dei dati per il backup e il ripristino delle applicazioni Kubernetes a NetApp ONTAP.
* Orchestrare i backup delle applicazioni locali e basati su storage di oggetti.
* Esegui il backup e il ripristino di intere applicazioni e singole risorse su qualsiasi cluster Kubernetes.
* Lavora con container e macchine virtuali in esecuzione su Kubernetes.
* Crea backup coerenti con l'applicazione utilizzando modelli e hook di esecuzione.


Per i dettagli sulla protezione dei carichi di lavoro di Kubernetes, fare riferimento a  https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-kubernetes-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro di Kubernetes"] .



=== 14 luglio 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



==== Dashboard del volume ONTAP migliorato

Ad aprile 2025 abbiamo lanciato un'anteprima di una Dashboard del volume ONTAP migliorata, molto più veloce ed efficiente.

Questa dashboard è stata progettata per supportare i clienti aziendali con un elevato numero di carichi di lavoro. Anche per i clienti con 20.000 volumi, la nuova dashboard si carica in meno di 10 secondi.

Dopo un'anteprima di successo e un feedback positivo da parte dei clienti, ora la stiamo rendendo l'esperienza predefinita per tutti i nostri clienti. Preparatevi per una dashboard incredibilmente veloce.

Per ulteriori informazioni, vedere link:br-use-dashboard.html["Visualizza lo stato di protezione nella Dashboard"].



==== Supporto del carico di lavoro di Microsoft SQL Server come anteprima tecnologica pubblica

Questa versione di BlueXP backup and recovery offre un'interfaccia utente aggiornata che consente di gestire i carichi di lavoro di Microsoft SQL Server utilizzando una strategia di protezione 3-2-1, già nota nel servizio di BlueXP backup and recovery . Con questa nuova versione, è possibile eseguire il backup di questi carichi di lavoro sullo storage primario, replicarli sullo storage secondario ed eseguirne il backup sullo storage di oggetti cloud.

Puoi iscriverti all'anteprima completando questo  https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["Anteprima del modulo di registrazione"^] .


NOTE: Questa documentazione sulla protezione dei carichi di lavoro di Microsoft SQL Server viene fornita come anteprima tecnologica. Con questa offerta di anteprima, NetApp si riserva il diritto di modificare dettagli, contenuti e tempistiche prima della disponibilità generale.

Questa versione di BlueXP backup and recovery include i seguenti aggiornamenti:

* *Funzionalità di backup 3-2-1*: questa versione integra le funzionalità SnapCenter , consentendo di gestire e proteggere le risorse SnapCenter con una strategia di protezione dei dati 3-2-1 dall'interfaccia utente BlueXP backup and recovery .
* *Importa da SnapCenter*: puoi importare i dati di backup e i criteri SnapCenter nel BlueXP backup and recovery.
* *Un'interfaccia utente riprogettata* offre un'esperienza più intuitiva per la gestione delle attività di backup e ripristino.
* *Destinazioni di backup*: puoi aggiungere bucket negli ambienti Amazon Web Services (AWS), Microsoft Azure Blob Storage, StorageGRID e ONTAP S3 da utilizzare come destinazioni di backup per i carichi di lavoro di Microsoft SQL Server.
* *Supporto per i carichi di lavoro*: questa versione consente di eseguire il backup, il ripristino, la verifica e la clonazione di database e gruppi di disponibilità di Microsoft SQL Server. (Il supporto per altri carichi di lavoro verrà aggiunto nelle versioni future.)
* *Opzioni di ripristino flessibili*: questa versione consente di ripristinare i database sia nelle posizioni originali che in quelle alternative in caso di danneggiamento o perdita accidentale dei dati.
* *Copie di produzione istantanee*: genera copie di produzione salvaspazio per sviluppo, test o analisi in pochi minuti anziché in ore o giorni.
* Questa versione include la possibilità di creare report dettagliati.


Per informazioni dettagliate sulla protezione dei carichi di lavoro di Microsoft SQL Server, vedere link:br-use-mssql-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro di Microsoft SQL Server"] .



=== 09 giugno 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



==== Aggiornamenti del supporto del catalogo indicizzato

A febbraio 2025, abbiamo introdotto la funzionalità di indicizzazione aggiornata (Catalogo indicizzato v2) da utilizzare durante il metodo di ripristino dei dati "Cerca e ripristina". La versione precedente ha migliorato significativamente le prestazioni di indicizzazione dei dati negli ambienti on-premise. Con questa versione, il catalogo di indicizzazione è ora disponibile negli ambienti Amazon Web Services, Microsoft Azure e Google Cloud Platform (GCP).

Se sei un nuovo cliente, il Catalogo Indicizzato v2 è abilitato per impostazione predefinita per tutti i nuovi ambienti. Se sei un cliente esistente, puoi reindicizzare il tuo ambiente per sfruttare il Catalogo Indicizzato v2.

.Come si attiva l'indicizzazione?
Prima di poter utilizzare il metodo Search & Restore per il ripristino dei dati, è necessario attivare l'indicizzazione in ogni ambiente di lavoro di origine da cui si prevede di ripristinare volumi o file. Selezionare l'opzione *Abilita indicizzazione* quando si esegue una ricerca e un ripristino.

Il catalogo indicizzato può quindi tenere traccia di ogni volume e file di backup, rendendo le ricerche rapide ed efficienti.

Per ulteriori informazioni, fare riferimento a https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["Abilita l'indicizzazione per Cerca e Ripristina"].



==== Endpoint di collegamento privato di Azure ed endpoint di servizio

In genere, il BlueXP backup and recovery stabiliscono un endpoint privato con il provider cloud per gestire le attività di protezione. Questa versione introduce un'impostazione opzionale che consente di abilitare o disabilitare la creazione automatica di un endpoint privato da parte di BlueXP Backup and Recovery. Questa opzione potrebbe essere utile se si desidera un maggiore controllo sul processo di creazione di endpoint privati.

È possibile abilitare o disabilitare questa opzione quando si abilita la protezione o si avvia il processo di ripristino.

Se si disabilita questa impostazione, è necessario creare manualmente l'endpoint privato affinché il backup e il ripristino di BlueXP funzionino correttamente. Senza una connettività adeguata, potrebbe non essere possibile eseguire correttamente le attività di backup e ripristino.



==== Supporto per SnapMirror su Cloud Resync su ONTAP S3

La versione precedente ha introdotto il supporto per SnapMirror to Cloud Resync (SM-C Resync). La funzionalità semplifica la protezione dei dati durante la migrazione dei volumi negli ambienti NetApp. Questa versione aggiunge il supporto per SM-C Resync su ONTAP S3 e su altri provider compatibili con S3, come Wasabi e MinIO.



==== Porta il tuo bucket per StorageGRID

Quando si creano file di backup nell'archiviazione oggetti per un ambiente di lavoro, per impostazione predefinita, BlueXP Backup and Recovery crea il contenitore (bucket o account di archiviazione) per i file di backup nell'account di archiviazione oggetti configurato. In precedenza, era possibile ignorare questa impostazione e specificare un contenitore personalizzato per Amazon S3, Azure Blob Storage e Google Cloud Storage. Con questa versione, è ora possibile utilizzare il proprio contenitore di archiviazione oggetti StorageGRID.

Vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-protect-journey.html["Crea il tuo contenitore di archiviazione di oggetti"].



== Classificazione



=== 14 luglio 2025



==== Versione 1,45

Questa versione BlueXP classification include modifiche al codice che ottimizzano l'utilizzo delle risorse e:

.Flusso di lavoro migliorato per aggiungere condivisioni di file per la scansione
Il flusso di lavoro per aggiungere condivisioni file a un gruppo di condivisione file è stato semplificato. Il processo ora differenzia anche il supporto del protocollo CIFS in base al tipo di autenticazione (Kerberos o NTLM).

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-file-shares.html["Eseguire la scansione delle condivisioni dei file"].

.Informazioni avanzate sul proprietario del file
Ora puoi visualizzare maggiori informazioni sui proprietari dei file acquisiti nella scheda Indagine. Quando visualizzi i metadati di un file nella scheda Indagine, individua il proprietario del file, quindi seleziona **Visualizza dettagli** per vedere il nome utente, l'e-mail e il nome dell'account SAM. Puoi anche visualizzare altri elementi di proprietà di questo utente. Questa funzionalità è disponibile solo per gli ambienti di lavoro con Active Directory.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Esaminare i dati memorizzati nella propria organizzazione"].



=== 10 giugno 2025



==== Versione 1,44

Questa versione di classificazione BlueXP  include:

.Tempi di aggiornamento migliorati per la dashboard di Governance
I tempi di aggiornamento per i singoli componenti della dashboard di Governance sono stati migliorati. La tabella seguente mostra la frequenza degli aggiornamenti per ciascun componente.

[cols="1,1"]
|===
| Componente | Tempi di aggiornamento 


| Età dei dati | 24 ore 


| Categorie | 24 ore 


| Panoramica dei dati | 5 minuti 


| File duplicati | 2 ore 


| Tipi di file | 24 ore 


| Dati non aziendali | 2 ore 


| Aprire permessi | 24 ore 


| Ricerche salvate | 2 ore 


| Dati sensibili e permessi estesi | 24 ore 


| Dimensione dei dati | 24 ore 


| Dati obsoleti | 2 ore 


| Principali repository di dati per livello di sensibilità | 2 ore 
|===
È possibile visualizzare l'ora dell'ultimo aggiornamento e aggiornare manualmente i componenti File duplicati, Dati non aziendali, Ricerche salvate, Dati obsoleti e Repository dati principali per livello di sensibilità. Per ulteriori informazioni sulla dashboard di Governance, consultare link:https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Visualizzare i dettagli di governance sui dati archiviati nell'organizzazione"] .

.Miglioramenti delle prestazioni e della sicurezza
Sono stati apportati miglioramenti per ottimizzare le prestazioni, il consumo di memoria e la sicurezza della classificazione BlueXP.

.Correzioni dei bug
Redis è stato aggiornato per migliorare l'affidabilità della classificazione BlueXP. La classificazione BlueXP ora utilizza Elasticsearch per migliorare l'accuratezza del reporting del conteggio dei file durante le scansioni.



=== 12 maggio 2025



==== Versione 1,43

Questa versione di classificazione BlueXP  include:

.Assegnare la priorità alle scansioni di classificazione
La classificazione BlueXP  supporta la possibilità di assegnare priorità alle scansioni Map & Classify oltre alle scansioni Mapping-only, consentendo di selezionare le scansioni da completare per prime. La prioritizzazione delle scansioni Map & Classify è supportata durante e prima dell'inizio delle scansioni. Se si sceglie di assegnare la priorità a una scansione mentre è in corso, vengono assegnate priorità sia alla scansione di mappatura che alla scansione di classificazione.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Assegnare priorità alle scansioni"].

.Supporto per categorie di dati canadesi per l'identificazione personale (PII)
Le scansioni di classificazione BlueXP  identificano le categorie di dati PII canadesi. Queste categorie includono informazioni bancarie, numeri di passaporto, numeri di assicurazione sociale, numeri di patente di guida e numeri di carta sanitaria per tutte le province e territori canadesi.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Categorie di dati personali"].

.Classificazione personalizzata (anteprima)
La classificazione BlueXP  supporta classificazioni personalizzate per le scansioni Map & Classify. Grazie alle classificazioni personalizzate, è possibile personalizzare le scansioni BlueXP  per acquisire dati specifici dell'organizzazione utilizzando espressioni regolari. Questa funzione è attualmente in anteprima.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["Aggiungere classificazioni personalizzate"].

.Scheda ricerche salvate
La scheda **Policies** è stata rinominata link:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["**Ricerche salvate**"]. La funzionalità rimane invariata.

.Inviare gli eventi di scansione alla timeline BlueXP 
La classificazione BlueXP  supporta l'invio di eventi di classificazione (quando viene avviata e terminata una scansione) a link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["Tempistiche di BlueXP"^].

.Aggiornamenti di protezione
* Il pacchetto keras è stato aggiornato, attenuando le vulnerabilità (BDSA-2025-0107 e BDSA-2025-1984).
* La configurazione dei container Docker è stata aggiornata. Il contenitore non ha più accesso alle interfacce di rete dell'host per la creazione di pacchetti di rete grezzi. Riducendo gli accessi non necessari, l'aggiornamento riduce i potenziali rischi di protezione.


.Miglioramenti delle performance
I miglioramenti del codice sono stati implementati per ridurre l'utilizzo della RAM e migliorare le prestazioni complessive della classificazione BlueXP .

.Correzioni dei bug
Sono stati corretti i bug che hanno causato il mancato funzionamento delle scansioni StorageGRID, il mancato caricamento delle opzioni del filtro della pagina di analisi e la valutazione del rilevamento dati per le valutazioni di volumi elevati.



=== 14 aprile 2025



==== Versione 1,42

Questa versione di classificazione BlueXP  include:

.Scansione in blocco per ambienti di lavoro
La classificazione BlueXP  supporta le operazioni bulk per gli ambienti di lavoro. È possibile scegliere di attivare le scansioni di mappatura, attivare le scansioni di mappatura e classificazione, disattivare le scansioni o creare una configurazione personalizzata tra i volumi in ambiente di lavoro. Se si effettua una selezione per un singolo volume, questa sovrascrive la selezione in blocco. Per eseguire un'operazione bulk, accedere alla pagina **Configurazione** ed effettuare la selezione.

.Scaricare il rapporto di indagine localmente
La classificazione BlueXP  supporta la possibilità di scaricare localmente i report di analisi dei dati da visualizzare nel browser. Se si sceglie l'opzione locale, l'analisi dei dati è disponibile solo nel formato CSV e visualizza solo le prime 10.000 righe di dati.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#create-the-data-investigation-report["Esaminare i dati memorizzati nella propria organizzazione con la classificazione BlueXP"].



=== 10 marzo 2025



==== Versione 1,41

Questa versione di classificazione BlueXP  include miglioramenti generali e correzioni dei bug. Include inoltre:

.Stato scansione
La classificazione BlueXP  tiene traccia dell'avanzamento in tempo reale delle scansioni di mappatura e classificazione _iniziali_ su un volume. Le barre progressive separate tengono traccia delle scansioni di mappatura e classificazione, presentando una percentuale di file totali sottoposti a scansione. È inoltre possibile passare il mouse su una barra di avanzamento per visualizzare il numero di file sottoposti a scansione e il numero totale di file. Il monitoraggio dello stato delle scansioni consente di ottenere informazioni più approfondite sull'avanzamento della scansione, consentendo di pianificare meglio le scansioni e di comprendere l'allocazione delle risorse.

Per visualizzare lo stato delle scansioni, accedere a **Configurazione** nella classificazione BlueXP , quindi selezionare **Configurazione ambiente di lavoro**. L'avanzamento viene visualizzato in linea per ogni volume.



=== 19 febbraio 2025



==== Versione 1,40

Questa versione di classificazione BlueXP  include i seguenti aggiornamenti.

.Supporto per RHEL 9,5
Questa versione fornisce il supporto per Red Hat Enterprise Linux v9,5 oltre alle versioni precedentemente supportate. Ciò è applicabile a qualsiasi installazione manuale in loco della classificazione BlueXP , comprese le implementazioni in ambienti oscuri.

I seguenti sistemi operativi richiedono l'utilizzo del motore del contenitore Podman e richiedono la classificazione BlueXP  versione 1,30 o superiore: Red Hat Enterprise Linux versione 8,8, 8,10, 9,0, 9,1, 9,2, 9,3, 9,4 e 9,5.

.Assegnare priorità alle scansioni di sola mappatura
Quando si eseguono scansioni solo mapping, è possibile assegnare la priorità alle scansioni più importanti. Questa funzione è utile quando si hanno molti ambienti di lavoro e si desidera garantire che le scansioni ad alta priorità vengano completate per prime.

Per impostazione predefinita, le scansioni vengono accodate in base all'ordine in cui vengono avviate. Con la possibilità di assegnare priorità alle scansioni, è possibile spostare le scansioni in primo piano nella coda. È possibile assegnare priorità a più scansioni. La priorità viene indicata in un ordine di primo ingresso e primo uscita, ovvero la prima scansione assegnata all'utente viene spostata in primo piano nella coda; la seconda scansione assegnata all'utente diventa seconda nella coda e così via.

La priorità viene concessa una tantum. Le riscansioni automatiche dei dati di mappatura vengono eseguite nell'ordine predefinito.

La prioritizzazione è limitata a link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["scansioni di sola mappatura"^]; non è disponibile per le scansioni mappa e classificazione.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Assegnare priorità alle scansioni"^].

.Riprovare tutte le scansioni
La classificazione BlueXP  supporta la possibilità di ripetere in batch tutte le scansioni non riuscite.

È possibile ripetere le scansioni in un'operazione batch con la funzione **Riprova tutto**. Se le scansioni di classificazione non vengono eseguite correttamente a causa di un problema temporaneo, ad esempio un'interruzione della rete, è possibile riprovare tutte le scansioni contemporaneamente con un solo pulsante invece di riprovare singolarmente. Le scansioni possono essere riavviate tutte le volte necessarie.

Per riprovare tutte le scansioni:

. Dal menu classificazione BlueXP , selezionare *Configurazione*.
. Per riprovare tutte le scansioni non riuscite, selezionare *Riprova tutte le scansioni*.


.Migliore precisione del modello di categorizzazione
La precisione del modello di machine learning per link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["categorie predefinite"] è migliorata del 11%.



=== 22 gennaio 2025



==== Versione 1,39

Questa versione di classificazione BlueXP  aggiorna il processo di esportazione per il rapporto analisi dati. Questo aggiornamento per l'esportazione è utile per eseguire analisi aggiuntive sui dati, creare visualizzazioni aggiuntive sui dati o condividere con altri i risultati dell'analisi dei dati.

In precedenza, l'esportazione del rapporto Data Investigation era limitata a 10.000 righe. Con questa versione, il limite è stato rimosso in modo da poter esportare tutti i dati. Questa modifica consente di esportare più dati dai report di analisi dei dati, offrendo maggiore flessibilità nell'analisi dei dati.

È possibile scegliere l'ambiente di lavoro, i volumi, la cartella di destinazione e il formato JSON o CSV. Il nome file esportato include un indicatore data e ora che consente di identificare quando i dati sono stati esportati.

Gli ambienti di lavoro supportati includono:

* Cloud Volumes ONTAP
* FSX per ONTAP
* ONTAP
* Gruppo di condivisione


L'esportazione dei dati dal rapporto di analisi dei dati presenta le seguenti limitazioni:

* Il numero massimo di record da scaricare è di 500 milioni. Per tipo (file, directory e tabelle)
* Si prevede che l'esportazione di un milione di record richiederà circa 35 minuti.


Per informazioni dettagliate sull'analisi dei dati e sul rapporto, vedere https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Esaminare i dati memorizzati nella propria organizzazione"].



=== 16 dicembre 2024



==== Versione 1,38

Questa versione di classificazione BlueXP  include miglioramenti generali e correzioni dei bug.



== Cloud Volumes ONTAP



=== 14 luglio 2025



==== Supporto per proxy trasparente

BlueXP ora supporta server proxy trasparenti oltre alle connessioni proxy esplicite esistenti. Durante la creazione o la modifica del connettore BlueXP , è possibile configurare un server proxy trasparente per gestire in modo sicuro il traffico di rete da e verso Cloud Volumes ONTAP.

Per ulteriori informazioni sull'utilizzo dei server proxy in Cloud Volumes ONTAP, fare riferimento a:

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-aws.html#network-configurations-to-support-connector-proxy-servers["Configurazioni di rete per supportare il proxy del connettore in AWS"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/azure/reference-networking-azure.html#network-configurations-to-support-connector["Configurazioni di rete per supportare il proxy del connettore in Azure"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-gcp.html#network-configurations-to-support-connector-proxy["Configurazioni di rete per supportare il proxy del connettore in Google Cloud"^]




==== Nuovo tipo di VM supportato per Cloud Volumes ONTAP in Azure

A partire da Cloud Volumes ONTAP 9.13.1, L8s_v3 è supportato come tipo di VM nelle zone di disponibilità singole e multiple di Azure, sia per le distribuzioni di coppie ad alta disponibilità (HA) nuove che esistenti.

Per ulteriori informazioni, fare riferimento a https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurazioni supportate in Azure"^].



=== 25 giugno 2025



==== Disponibilità limitata delle licenze BYOL per Cloud Volumes ONTAP

A partire dal 25 giugno 2025, NetApp ha limitato il modello di licenza Bring Your Own License (BYOL) per Cloud Volumes ONTAP. La restrizione si applica a tutti i clienti e a tutte le distribuzioni Cloud Volumes ONTAP in AWS, Azure e Google Cloud. Le uniche eccezioni riguardano i clienti del settore pubblico statunitense e le distribuzioni nella regione Cina.

Il supporto e i servizi NetApp continueranno fino alla scadenza del contratto BYOL, ma le licenze scadute non verranno rinnovate né estese. Alla scadenza delle licenze BYOL, è necessario sostituirle con licenze basate sulla capacità acquistate tramite gli abbonamenti al marketplace cloud. Un modello di licenza basato sulla capacità, tramite i marketplace hyperscaler, semplifica l'esperienza di gestione delle licenze e offre maggiori vantaggi aziendali. Contatta il team Account NetApp o i rappresentanti del Customer Success per discutere le opzioni di conversione.

Per ulteriori informazioni, fare riferimento a questo comunicato clienti:  https://mysupport.netapp.com/info/communications/CPC-00661.html["CPC-00661: Modifiche alla politica BYOL Cloud Volumes ONTAP"^] .



=== 29 maggio 2025



==== Implementazioni in modalità privata abilitate per Cloud Volumes ONTAP 9.15.1

Ora puoi implementare Cloud Volumes ONTAP 9.15.1 in modalità privata in AWS, Azure e Google Cloud. La modalità privata è abilitata per implementazioni a nodo singolo e high Availability (ha) di Cloud Volumes ONTAP 9.15.1.

Per ulteriori informazioni sulle implementazioni in modalità privata, fare riferimento a https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#restricted-mode["Scopri le modalità di implementazione di BlueXP"^].



== Cloud Volumes Service per Google Cloud



=== 9 settembre 2020



==== Supporto per Cloud Volumes Service per Google Cloud

Ora puoi gestire Cloud Volumes Service per Google Cloud direttamente da BlueXP:

* Configurare e creare un ambiente di lavoro
* Creare e gestire volumi NFSv3 e NFSv4.1 per client Linux e UNIX
* Creare e gestire volumi SMB 3.x per client Windows
* Creare, eliminare e ripristinare le snapshot dei volumi




== Copia e sincronizzazione



=== 2 febbraio 2025



==== Supporto di nuovi sistemi operativi per il broker di dati

Il broker di dati è ora supportato sugli host che eseguono Red Hat Enterprise 9,4, Ubuntu 23,04 e Ubuntu 24,04.

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Visualizza i requisiti dell'host Linux"].



=== 27 ottobre 2024



==== Correzioni dei bug

Abbiamo aggiornato il servizio di copia e sincronizzazione di BlueXP e il broker di dati per risolvere alcuni bug. La nuova versione del broker di dati è la 1,0.56.



=== 16 settembre 2024



==== Correzioni dei bug

Abbiamo aggiornato il servizio di copia e sincronizzazione di BlueXP e il broker di dati per risolvere alcuni bug. La nuova versione del broker di dati è la 1,0.55.



== Consulente digitale



=== 09 luglio 2025



==== Upgrade Advisor

* È stata inclusa un'opzione di download multiformato per i piani Upgrade Advisor, per semplificare la pianificazione degli aggiornamenti ONTAP e risolvere potenziali problemi o avvisi. Ora è possibile scaricare i piani Upgrade Advisor nei formati Excel, PDF e JSON.
* Nel formato Excel del piano Upgrade Advisor sono stati apportati i seguenti miglioramenti:
+
** È possibile visualizzare i controlli preliminari eseguiti sul cluster, contrassegnando i risultati con indicatori come "Superato", "Non superato" o "Saltato". Questo garantisce che il cluster sia in condizioni ottimali per completare l'aggiornamento ONTAP .
** È possibile visualizzare gli ultimi aggiornamenti firmware consigliati e applicabili al cluster, insieme alla versione fornita con la versione di destinazione ONTAP .
** È stata aggiunta una nuova scheda che offre controlli di interoperabilità per i cluster SAN. Fornisce una visualizzazione delle versioni del sistema operativo host supportate per la versione ONTAP di destinazione selezionata.






=== 08 maggio 2025



==== Widget AutoSupport

Il widget AutoSupport è stato migliorato per includere una finestra a comparsa per fornire dettagli sui sistemi che hanno interrotto l'invio di dati AutoSupport. L'abilitazione di AutoSupport riduce i rischi di downtime e supporta una gestione proattiva dello stato del sistema.



==== Report contratti di supporto

Il report dei contratti di supporto è stato migliorato per includere il nuovo campo flag ASP/LSG. Questo campo consente di filtrare e identificare i sistemi coperti da un partner di supporto autorizzato, noto anche come Lifecycle Services Certified.



==== Dashboard sulla sostenibilità

È ora possibile avviare il dashboard Sustainability utilizzando il collegamento incluso nella presentazione Sustainability.



=== 05 marzo 2025



==== Upgrade Advisor

* Utilizzando il Disk Qualification Package (DQP), è ora possibile aggiornare automaticamente i controller del disco e il firmware del dispositivo di archiviazione in base a criteri predefiniti di integrità e prestazioni. Ciò riduce i potenziali guasti e migliora l'affidabilità generale del sistema.
* Il database dei fusi orari (DB) è stato introdotto per mantenere automaticamente l'allineamento del sistema con le definizioni dei fusi orari più recenti. Ciò garantisce che le operazioni dipendenti dal tempo continuino senza problemi anche quando le regole del fuso orario cambiano.




== Portafoglio digitale



=== 10 marzo 2025



==== Possibilità di rimuovere gli abbonamenti

Ora puoi rimuovere gli abbonamenti dal portafoglio digitale se hai annullato l'iscrizione.



==== Visualizza la capacità consumata per gli abbonamenti Marketplace

Quando visualizzi gli abbonamenti PAYGO, puoi ora visualizzare la capacità consumata dell'abbonamento.



=== 10 febbraio 2025

Il portafoglio digitale di BlueXP  è stato riprogettato per garantire facilità d'uso e ora offre funzionalità aggiuntive di gestione delle licenze e delle sottoscrizioni.



==== Nuova dashboard Panoramica

La home page del portafoglio digitale dispone di una dashboard aggiornata delle licenze NetApp e delle iscrizioni al marketplace, con la possibilità di analizzare in dettaglio servizi, tipi di licenza e azioni richieste.



==== Configurazione delle sottoscrizioni alle credenziali

Il Digital Wallet di BlueXP  consente ora di configurare le iscrizioni per le credenziali del provider. In genere, questa operazione viene eseguita quando si sottoscrive per la prima volta un abbonamento a Marketplace o un contratto annuale. In precedenza, la modifica delle credenziali dell'abbonamento poteva essere effettuata solo nella pagina credenziali.



==== Associazione delle sottoscrizioni alle organizzazioni

Ora puoi aggiornare l'organizzazione a cui è associato un abbonamento direttamente dal portafoglio digitale.



==== Gestione delle licenze di Cloud Volume ONTAP

Ora è possibile gestire le licenze Cloud Volumes ONTAP tramite la home page o la scheda *licenze dirette*. Utilizzare la scheda *Marketplace sottoscrizioni* per visualizzare le informazioni relative all'abbonamento.



=== 5 marzo 2024



==== Disaster recovery di BlueXP

Ora il Digital Wallet di BlueXP ti permette di gestire le licenze per il disaster recovery di BlueXP. Puoi aggiungere licenze, aggiornare le licenze e visualizzare i dettagli sulla capacità concessa in licenza.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Scopri come gestire le licenze per i servizi dati BlueXP"]



=== 30 luglio 2023



==== Miglioramenti dei report sull'utilizzo

Sono ora disponibili diversi miglioramenti ai report sull'utilizzo di Cloud Volumes ONTAP:

* L'unità TIB è ora inclusa nel nome delle colonne.
* È ora incluso un nuovo campo _node(s)_ per i numeri di serie.
* Una nuova colonna _workload Type_ è ora inclusa nel report sull'utilizzo delle VM di storage.
* I nomi degli ambienti di lavoro sono ora inclusi nei report sull'utilizzo delle VM di storage e dei volumi.
* Il tipo di volume _file_ è ora denominato _Primary (Read/Write)_.
* Il tipo di volume _secondario_ è ora denominato _secondario (DP)_.


Per ulteriori informazioni sui report sull'utilizzo, fare riferimento a. https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Scarica i report sull'utilizzo"].



== Disaster recovery



=== 14 luglio 2025

Versione 4.2.5



==== Ruoli utente nel BlueXP disaster recovery

Il BlueXP disaster recovery ora utilizza ruoli per gestire l'accesso di ciascun utente a specifiche funzionalità e azioni.

Il servizio utilizza i seguenti ruoli specifici per il BlueXP disaster recovery.

* *Amministratore del ripristino di emergenza*: esegue qualsiasi azione nel BlueXP disaster recovery.
* *Amministratore del failover del disaster recovery*: esegue azioni di failover e migrazione nel BlueXP disaster recovery.
* *Amministratore dell'applicazione di disaster recovery*: crea e modifica piani di replica e avvia failover di prova.
* *Visualizzatore di disaster recovery*: visualizza le informazioni nel BlueXP disaster recovery, ma non può eseguire alcuna azione.


Se si fa clic sul servizio BlueXP disaster recovery e lo si configura per la prima volta, è necessario disporre dell'autorizzazione *SnapCenterAdmin* o del ruolo di *Organization Admin*.

Per ulteriori informazioni, vedere  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Ruoli utente e autorizzazioni nel BlueXP disaster recovery"].

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Scopri i ruoli di accesso BlueXP per tutti i servizi"^].



==== Altri aggiornamenti nel BlueXP disaster recovery

* Rilevamento della rete migliorato
* Miglioramenti della scalabilità:
+
** Filtraggio per i metadati richiesti anziché per tutti i dettagli
** Miglioramenti della scoperta per recuperare e aggiornare più velocemente le risorse della VM
** Ottimizzazione della memoria e delle prestazioni per il recupero e l'aggiornamento dei dati
** Miglioramenti nella creazione del client e nella gestione del pool di vCenter SDK


* Gestione dei dati obsoleti alla prossima individuazione programmata o manuale:
+
** Quando una VM viene eliminata in vCenter, la BlueXP disaster recovery ora la rimuove automaticamente dal piano di replica.
** Quando un datastore o una rete vengono eliminati in vCenter, la BlueXP disaster recovery li elimina ora dal piano di replica e dal gruppo di risorse.
** Quando un cluster, un host o un data center viene eliminato in vCenter, la BlueXP disaster recovery lo elimina ora dal piano di replica e dal gruppo di risorse.


* Ora puoi accedere alla documentazione di Swagger in modalità di navigazione in incognito. Puoi accedervi da BlueXP disaster recovery tramite l'opzione Impostazioni > Documentazione API o direttamente al seguente URL in modalità di navigazione in incognito:  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Documentazione Swagger"^] .
* In alcune situazioni, dopo un'operazione di failback, l'iGroup veniva lasciato indietro al termine dell'operazione. Questo aggiornamento rimuove l'iGroup se è obsoleto.
* Se il nome di dominio completo NFS è stato utilizzato nel piano di replica, il BlueXP disaster recovery ora lo risolve in un indirizzo IP. Questo aggiornamento è utile se il nome di dominio completo non è risolvibile nel sito di disaster recovery.
* Miglioramenti dell'allineamento dell'interfaccia utente
* Miglioramenti del registro per acquisire i dettagli delle dimensioni di vCenter dopo la scoperta riuscita




=== 30 giugno 2025

Versione 4.2.4P2



==== Miglioramenti della scoperta

Questo aggiornamento migliora il processo di individuazione, riducendone i tempi necessari.



=== 23 giugno 2025

Versione 4.2.4P1



==== Miglioramenti della mappatura delle subnet

Questo aggiornamento migliora la finestra di dialogo "Aggiungi e modifica mappatura subnet" con una nuova funzionalità di ricerca. Ora è possibile trovare rapidamente subnet specifiche inserendo termini di ricerca, semplificando la gestione delle mappature subnet.



=== 9 giugno 2025

Versione 4.2.4



==== Supporto per la soluzione password dell'amministratore locale di Windows (LAPS)

Windows Local Administrator Password Solution (Windows LAPS) è una funzionalità di Windows che gestisce ed esegue automaticamente il backup della password di un account amministratore locale su Active Directory.

Ora puoi selezionare le opzioni di mappatura della subnet e selezionare l'opzione LAPS fornendo i dettagli del controller di dominio. Con questa opzione, non è necessario fornire una password per ciascuna delle macchine virtuali.

Per ulteriori informazioni, fare riferimento alla https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replica"].



== Sistemi e-Series



=== 12 maggio 2025



==== Ruolo di accesso BlueXP necessario

Per visualizzare, scoprire o gestire E-Series in BlueXP, ora è necessario uno dei seguenti ruoli di accesso: amministratore dell'organizzazione, amministratore di cartelle o progetti, amministratore di archiviazione o specialista dell'integrità del sistema.  https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso BlueXP."^]



=== 18 settembre 2022



==== Supporto per e-Series

Ora puoi scoprire i tuoi sistemi e-Series direttamente da BlueXP. La scoperta dei sistemi e-Series ti offre una vista completa dei dati nel tuo multicloud ibrido.



== Efficienza economica



=== 15 maggio 2024



==== Funzioni disattivate

Alcune caratteristiche di efficienza economica di BlueXP  sono state temporaneamente disattivate:

* Aggiornamento tecnologico
* Aggiungere capacità




=== 14 marzo 2024



==== Opzioni di aggiornamento tecnologico

Se disponi di risorse esistenti e vuoi determinare se una tecnologia deve essere aggiornata, puoi usare le opzioni di refresh della tecnologia dell'efficienza economica di BlueXP. Puoi rivedere una breve valutazione dei tuoi carichi di lavoro attuali e ottenere consigli, oppure, se hai inviato log di AutoSupport a NetApp negli ultimi 90 giorni, il servizio può ora fornire una simulazione dei carichi di lavoro per vedere le performance dei tuoi carichi di lavoro sul nuovo hardware.

È anche possibile aggiungere un carico di lavoro ed escludere i carichi di lavoro esistenti dalla simulazione.

In precedenza, era possibile solo effettuare una valutazione delle risorse e stabilire se si consiglia un refresh tecnologico.

La funzione è ora parte dell'opzione aggiornamento tecnico nel menu di navigazione a sinistra.

Ulteriori informazioni su https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Valutazione di un refresh tecnologico"] .



=== 08 novembre 2023



==== Aggiornamento tecnologico

Questa release dell'efficienza economica di BlueXP include una nuova opzione per valutare gli asset e identificare se si consiglia un refresh tecnologico. Il servizio include una nuova opzione di aggiornamento tecnico nel riquadro a sinistra, nuove pagine in cui è possibile effettuare una valutazione dei carichi di lavoro e delle risorse correnti e un report che fornisce consigli.



== Caching edge

Il servizio di caching edge di BlueXP  è stato rimosso il 7 agosto 2024.



== Storage Google Cloud



=== 10 luglio 2023



==== Possibilità di aggiungere nuovi bucket e gestire i bucket esistenti da BlueXP

Hai avuto la possibilità di visualizzare i bucket di storage di Google Cloud su BlueXP Canvas per un bel po' di tempo. Ora è possibile aggiungere nuovi bucket e modificare le proprietà per i bucket esistenti direttamente da BlueXP . https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["Scopri come aggiungere nuovi bucket di storage Google Cloud"].



== Keystone



=== 19 giugno 2025



==== Dashboard Keystone in BlueXP

Ora puoi accedere alla dashboard di Keystone direttamente da BlueXP. Questa integrazione ti offre un unico punto di monitoraggio, gestione e tracciamento di tutti i tuoi abbonamenti Keystone e degli altri servizi NetApp.

Con la dashboard Keystone in BlueXP puoi:

* Visualizza tutti i dettagli del tuo abbonamento, l'utilizzo della capacità e le risorse in un unico posto.
* Gestisci facilmente gli abbonamenti e richiedi modifiche in base all'evoluzione delle tue esigenze.
* Rimani aggiornato sulle ultime informazioni relative al tuo ambiente di archiviazione.


Per iniziare, vai su *Archiviazione > Keystone* nel menu di navigazione a sinistra di BlueXP. Per ulteriori informazioni, fare riferimento a link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Panoramica della dashboard Keystone"].



== Kubernetes

Il supporto per rilevare e gestire i cluster Kubernetes è stato rimosso il 7 agosto 2024.



== Report sulla migrazione

Il servizio di report sulla migrazione BlueXP  è stato rimosso il 7 agosto 2024.



== Cluster ONTAP on-premise



=== 12 maggio 2025



==== Ruolo di accesso BlueXP necessario

Per visualizzare, individuare o gestire i cluster ONTAP locali, ora è necessario uno dei seguenti ruoli di accesso: amministratore dell'organizzazione, amministratore di cartelle o progetti, amministratore di archiviazione o specialista dell'integrità del sistema. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Scopri di più sui ruoli di accesso BlueXP."^]



=== 26 novembre 2024



==== Supporto per sistemi ASA R2 in modalità privata

È ora possibile scoprire i sistemi NetApp ASA R2 quando si utilizza BlueXP  in modalità privata. Questo supporto è disponibile a partire dalla versione 3.9.46 di BlueXP  in modalità privata.

* https://docs.netapp.com/us-en/asa-r2/index.html["Scopri di più sui sistemi ASA R2"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Scopri le modalità di implementazione di BlueXP"^]




=== 7 ottobre 2024



==== Supporto per i sistemi ASA R2

È ora possibile scoprire i sistemi NetApp ASA R2 in BlueXP  quando si utilizza BlueXP  in modalità standard o limitata. Dopo aver scoperto un sistema NetApp ASA R2 e aperto l'ambiente di lavoro, verrai indirizzato direttamente a Gestione sistema.

Non sono disponibili altre opzioni di gestione con i sistemi ASA R2. Non è possibile utilizzare la vista Standard e non è possibile attivare i servizi BlueXP.

Il rilevamento dei sistemi ASA R2 non è supportato quando si utilizza BlueXP  in modalità privata.

* https://docs.netapp.com/us-en/asa-r2/index.html["Scopri di più sui sistemi ASA R2"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Scopri le modalità di implementazione di BlueXP"^]




== Resilienza operativa



=== 02 aprile 2023



==== Servizio di resilienza operativa di BlueXP

Utilizzando il nuovo servizio di resilienza operativa BlueXP e i suoi suggerimenti per la risoluzione automatizzata dei rischi operativi IT, è possibile implementare le soluzioni suggerite prima che si verifichi un'interruzione o un guasto.

La resilienza operativa è un servizio che consente di analizzare avvisi ed eventi per mantenere lo stato di salute, l'uptime e le performance di servizi e soluzioni.

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["Scopri di più sulla resilienza operativa di BlueXP"].



== Protezione ransomware



=== 15 luglio 2025



==== Supporto del carico di lavoro SAN

Questa versione include il supporto per i carichi di lavoro SAN nella BlueXP ransomware protection. Ora è possibile proteggere i carichi di lavoro SAN oltre ai carichi di lavoro NFS e CIFS.

Per ulteriori informazioni, fare riferimento a link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["Prerequisiti della protezione dal ransomware di BlueXP"].



==== Protezione migliorata del carico di lavoro

Questa versione migliora il processo di configurazione per i carichi di lavoro con policy di snapshot e backup provenienti da altri strumenti NetApp , come SnapCenter o BlueXP backup and recovery. Nelle versioni precedenti, la BlueXP ransomware protection rilevava le policy di altri strumenti, consentendo solo di modificare la policy di rilevamento. Con questa versione, è ora possibile sostituire le policy di snapshot e backup con le policy BlueXP ransomware protection o continuare a utilizzare le policy di altri strumenti.

Per ulteriori informazioni, fare riferimento alla link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["Proteggere i carichi di lavoro"].



==== Notifiche via email

Se la BlueXP ransomware protection rileva un possibile attacco, viene visualizzata una notifica nelle Notifiche BlueXP e viene inviata un'e-mail all'indirizzo e-mail configurato.

L'e-mail include informazioni sulla gravità, sul carico di lavoro interessato e un link all'avviso nella scheda *Avvisi* della BlueXP ransomware protection .

Se hai configurato un sistema di sicurezza e gestione degli eventi (SIEM) nella BlueXP ransomware protection, il servizio invia i dettagli dell'avviso al tuo sistema SIEM.

Per ulteriori informazioni, fare riferimento alla link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Gestisci gli avvisi di ransomware rilevati"].



=== 9 giugno 2025



==== Aggiornamenti della landing page

Questa versione include aggiornamenti alla landing page per la protezione dal ransomware BlueXP che semplificano l'avvio della prova gratuita e la scoperta.



==== Aggiornamenti sulle esercitazioni di preparazione

In precedenza, era possibile eseguire un'esercitazione di preparazione al ransomware simulando un attacco su un nuovo carico di lavoro campione. Con questa funzionalità, è possibile analizzare l'attacco simulato e ripristinare il carico di lavoro. Utilizza questa funzionalità per testare le notifiche di avviso, la risposta e il ripristino. Eseguire e pianificare queste esercitazioni con la frequenza necessaria.

Con questa versione, puoi utilizzare un nuovo pulsante sulla Dashboard di protezione ransomware di BlueXP per eseguire un'esercitazione di preparazione al ransomware su un carico di lavoro di prova, semplificando la simulazione di attacchi ransomware, l'analisi del loro impatto e il ripristino efficiente dei carichi di lavoro, il tutto all'interno di un ambiente controllato.

Oltre ai carichi di lavoro NFS, ora è possibile eseguire esercitazioni di preparazione sui carichi di lavoro CIFS (SMB).

Per ulteriori informazioni, fare riferimento alla https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Condurre un'indagine sulla preparazione all'attacco ransomware"].



==== Abilita gli aggiornamenti della classificazione BlueXP

Prima di utilizzare la classificazione BlueXP  all'interno del servizio di protezione dal ransomware BlueXP , devi abilitare la classificazione BlueXP  per eseguire la scansione dei tuoi dati. La classificazione dei dati aiuta a trovare informazioni di identificazione personale (PII), il che può aumentare i rischi per la sicurezza.

È possibile distribuire la classificazione BlueXP su un carico di lavoro di condivisione file dall'interno della protezione ransomware BlueXP. Nella colonna *Esposizione privacy*, selezionare l'opzione *Identifica esposizione*. Se è stato abilitato il servizio di classificazione, questa azione identifica l'esposizione. In caso contrario, con questa versione, una finestra di dialogo presenta l'opzione per distribuire la classificazione BlueXP. Selezionare *Distribuisci* per accedere alla pagina di destinazione del servizio di classificazione BlueXP, dove è possibile distribuire tale servizio. W

Per i dettagli, fare riferimento a  https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["Implementare la classificazione BlueXP nel cloud"^] e per utilizzare il servizio all'interno della protezione ransomware BlueXP, fare riferimento a  https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["Eseguire la scansione delle informazioni di identificazione personale con la classificazione BlueXP"] .



=== 13 maggio 2025



==== Report sugli ambienti di lavoro non supportati nella protezione dal ransomware BlueXP

Durante il flusso di lavoro di rilevamento, la protezione ransomware BlueXP  riporta ulteriori dettagli durante il passaggio con il mouse sui carichi di lavoro supportati o non supportati. Questo ti aiuterà a capire perché alcuni dei tuoi workload non vengono scoperti dal servizio di protezione ransomware di BlueXP .

Ci sono molti motivi per cui il servizio non supporta un ambiente di lavoro, ad esempio, la versione di ONTAP nell'ambiente di lavoro potrebbe essere inferiore alla versione richiesta. Quando si passa con il mouse su un ambiente di lavoro non supportato, viene visualizzata una descrizione comandi.

È possibile visualizzare gli ambienti di lavoro non supportati durante il rilevamento iniziale, in cui è anche possibile scaricare i risultati. È inoltre possibile visualizzare i risultati del rilevamento dall'opzione *rilevamento carico di lavoro* nella pagina Impostazioni.

Per ulteriori informazioni, fare riferimento alla https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Rileva i carichi di lavoro nella protezione dal ransomware di BlueXP"].



=== 29 aprile 2025



==== Supporto per Amazon FSX per NetApp ONTAP

Questa versione supporta Amazon FSX per NetApp ONTAP. Questa funzionalità ti aiuta a proteggere i workload FSX per ONTAP con la protezione dal ransomware BlueXP .

FSX per ONTAP è un servizio completamente gestito che offre la potenza dello storage NetApp ONTAP nel cloud. Offre le stesse caratteristiche, performance e funzionalità amministrative che utilizzi on-premise con l'agilità e la scalabilità di un servizio AWS nativo.

Sono state apportate le seguenti modifiche al flusso di lavoro di protezione ransomware BlueXP :

* Il rilevamento include i carichi di lavoro in FSX per gli ambienti di lavoro ONTAP 9,15.
* La scheda protezione mostra i carichi di lavoro in FSX per gli ambienti ONTAP. In questo ambiente occorre eseguire le operazioni di backup usando il servizio di backup FSX per ONTAP. Puoi ripristinare questi workload utilizzando gli snapshot di protezione ransomware BlueXP .
+

TIP: Le policy di backup di un carico di lavoro in esecuzione su FSX per ONTAP non possono essere impostate in BlueXP . Tutte le policy di backup esistenti impostate in Amazon FSX per NetApp ONTAP rimangono invariate.

* Gli incidenti di avviso mostrano il nuovo ambiente di lavoro FSX per ONTAP.


Per ulteriori informazioni, fare riferimento alla https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["Scopri di più sulla protezione dal ransomware e sugli ambienti di lavoro di BlueXP"].

Per informazioni sulle opzioni supportate, fare riferimento alla https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["Limiti di protezione dal ransomware BlueXP"] .



==== Ruolo di accesso BlueXP necessario

Ora è necessario uno dei seguenti ruoli di accesso per visualizzare, scoprire o gestire la protezione ransomware BlueXP: amministratore dell'organizzazione, amministratore di cartelle o progetti, amministratore della protezione ransomware o visualizzatore della protezione ransomware.

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Scopri i ruoli di accesso BlueXP per tutti i servizi"^].



=== 14 aprile 2025



==== Report di preparazione

Con questa release, puoi esaminare i report dettagliati sulla preparazione agli attacchi ransomware. Un'esercitazione di preparazione consente di simulare un attacco ransomware su un carico di lavoro di esempio appena creato. Quindi, esaminare l'attacco simulato e recuperare il carico di lavoro del campione. Questa funzionalità ti aiuta a essere preparato in caso di un attacco ransomware effettivo, testando i processi di notifica, risposta e recovery degli avvisi.

Per ulteriori informazioni, fare riferimento alla https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Condurre un'indagine sulla preparazione all'attacco ransomware"].



==== Nuovi ruoli e autorizzazioni per il controllo degli accessi basati sui ruoli

In precedenza potresti assegnare ruoli e autorizzazioni agli utenti in base alle loro responsabilità, aiutandoti a gestire l'accesso degli utenti alla protezione dal ransomware di BlueXP . Con questa release, ci sono due nuovi ruoli specifici della protezione ransomware BlueXP  con autorizzazioni aggiornate. I nuovi ruoli sono:

* Amministratore della protezione dal ransomware
* Visualizzatore di protezione dal ransomware


Per ulteriori informazioni sulle autorizzazioni, fare riferimento alla sezione https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["Accesso alle funzionalità della protezione ransomware BlueXP  in base al ruolo"] .



==== Miglioramenti dei pagamenti

Questa versione include diversi miglioramenti al processo di pagamento.

Per ulteriori informazioni, fare riferimento alla https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["Impostare le opzioni di licenza e pagamento"].



== Risoluzione dei problemi

Il servizio di correzione di BlueXP è stato rimosso il 22 aprile 2024.



== Replica



=== 18 settembre 2022



==== FSX per ONTAP to Cloud Volumes ONTAP

Ora puoi replicare i dati da un file system Amazon FSX per ONTAP a Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Scopri come configurare la replica dei dati"].



=== 31 luglio 2022



==== FSX per ONTAP come origine dati

Ora puoi replicare i dati da un file system Amazon FSX per ONTAP nelle seguenti destinazioni:

* Amazon FSX per ONTAP
* Cluster ONTAP on-premise


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Scopri come configurare la replica dei dati"].



=== 2 settembre 2021



==== Supporto per Amazon FSX per ONTAP

Ora puoi replicare i dati da un sistema Cloud Volumes ONTAP o un cluster ONTAP on-premise su un file system Amazon FSX per ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Scopri come configurare la replica dei dati"].



== Aggiornamenti software



=== 12 maggio 2025



==== Ruolo di accesso BlueXP necessario

Ora è necessario uno dei seguenti ruoli di accesso per installare gli aggiornamenti software: *Amministratore organizzazione*, *Amministratore cartella o progetto*, *Amministratore archiviazione*, *Visualizzatore archiviazione* o *Specialista integrità archiviazione*. Gli utenti con il ruolo di Visualizzatore archiviazione dispongono di diverse autorizzazioni relative agli aggiornamenti software, ma non possono installarli. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Scopri di più sui ruoli di accesso BlueXP."^]



=== 02 aprile 2025



==== Rischi mitigati

Nella sezione riepilogativa degli aggiornamenti software BlueXP , è ora possibile visualizzare il numero totale di rischi che possono essere mitigati dall'aggiornamento del sistema operativo. Ciò consente agli utenti di valutare i miglioramenti della sicurezza e della stabilità nella base di installazione.



=== 07 agosto 2024



==== Aggiornamento ONTAP

Il servizio di aggiornamenti software di BlueXP  offre agli utenti un'esperienza di aggiornamento senza problemi, riducendo i rischi e garantendo ai clienti la possibilità di sfruttare appieno le funzionalità di ONTAP.

Ulteriori informazioni su link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Aggiornamenti software BlueXP"].



== StorageGRID



=== 12 maggio 2025



==== Ruoli di accesso BlueXP necessari

Ora è necessario uno dei seguenti ruoli di accesso per visualizzare, scoprire o gestire StorageGRID in BlueXP: *Amministratore organizzazione*, *Amministratore cartella o progetto*, *Amministratore archiviazione* o *Specialista integrità archiviazione*. link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso BlueXP."^]



=== 7 agosto 2024



==== Nuova vista avanzata

A partire da StorageGRID 11,8, è possibile utilizzare la familiare interfaccia di gestione griglia per gestire il sistema StorageGRID da BlueXP .

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Informazioni su come amministrare StorageGRID utilizzando la visualizzazione avanzata"].



==== Possibilità di rivedere e approvare il certificato dell'interfaccia di gestione StorageGRID

È ora possibile esaminare e approvare un certificato dell'interfaccia di gestione StorageGRID quando si rileva il sistema StorageGRID da BlueXP . È inoltre possibile esaminare e approvare il certificato più recente dell'interfaccia di gestione StorageGRID in una griglia scoperta.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Informazioni su come esaminare e approvare il certificato del server durante il rilevamento del sistema."]



=== 18 settembre 2022



==== Supporto per StorageGRID

Ora puoi scoprire i tuoi sistemi StorageGRID direttamente da BlueXP. Discovering StorageGRID ti offre una vista completa dei dati nel tuo multicloud ibrido.



== Tiering



=== 9 agosto 2023



==== Utilizzare un prefisso personalizzato per il nome del bucket

In passato era necessario utilizzare il prefisso predefinito "fabric-pool" per definire il nome del bucket, ad esempio _fabric-pool-bucket1_. Ora è possibile utilizzare un prefisso personalizzato per assegnare un nome al bucket. Questa funzionalità è disponibile solo con il tiering dei dati su Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Scopri di più"].



==== Cerca un cluster in tutti i connettori BlueXP

Se si utilizzano più connettori per gestire tutti i sistemi storage del proprio ambiente, alcuni cluster in cui si desidera implementare il tiering potrebbero trovarsi in diversi connettori. Se non sai con certezza quale connettore gestisce un determinato cluster, puoi cercare in tutti i connettori utilizzando il tiering BlueXP. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Scopri di più"].



=== 4 luglio 2023



==== Regolare la larghezza di banda per trasferire i dati inattivi

Quando si attiva il tiering BlueXP, ONTAP può utilizzare una quantità illimitata di larghezza di banda di rete per trasferire i dati inattivi dai volumi nel cluster allo storage a oggetti. Se noti che il traffico di tiering sta influenzando i normali carichi di lavoro degli utenti, puoi ridurre la quantità di larghezza di banda che può essere utilizzata durante il trasferimento. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Scopri di più"].



==== Evento di tiering visualizzato nel Centro notifiche

L'evento di tiering "Tiering additional data from cluster <name> to object storage to aumento your storage efficiency" viene ora visualizzato come notifica quando un cluster tiering meno del 20% dei suoi dati cold - compresi i cluster che non tierano dati.

Questa notifica è un "consiglio" per rendere i sistemi più efficienti e risparmiare sui costi di storage. Fornisce un collegamento a https://bluexp.netapp.com/cloud-tiering-service-tco["Calcolo del costo totale di proprietà e del risparmio di BlueXP Tiering"^] per aiutarti a calcolare i risparmi sui costi.



=== 3 aprile 2023



==== La scheda Licensing (licenze) è stata rimossa

La scheda Licensing (licenze) è stata rimossa dall'interfaccia di tiering BlueXP. Tutte le licenze per gli abbonamenti pay-as-you-go (PAYGO) sono accessibili subito dal pannello di controllo on-premise di BlueXP Tiering. Da questa pagina è inoltre disponibile un collegamento al portafoglio digitale BlueXP, che consente di visualizzare e gestire qualsiasi tipo di licenza BYOL (Bring-Your-Own-licenses) BlueXP tiering.



==== Le schede di tiering sono state rinominate e aggiornate

La scheda "Clusters Dashboard" è stata rinominata "Clusters" e la scheda "on-Prem Overview" è stata rinominata "on-premise Dashboard". In queste pagine sono state aggiunte alcune informazioni utili per valutare se è possibile ottimizzare lo spazio di storage con una configurazione di tiering aggiuntiva.



== Caching dei volumi



=== 04 giugno 2023



==== Caching dei volumi

Il caching dei volumi, una funzionalità del software ONTAP 9, è una funzionalità di caching remoto che semplifica la distribuzione dei file, riduce la latenza WAN avvicinando le risorse a dove si trovano gli utenti e le risorse di calcolo e riduce i costi della larghezza di banda della WAN. Il caching dei volumi fornisce un volume persistente e scrivibile in un luogo remoto. È possibile utilizzare il caching dei volumi BlueXP per accelerare l'accesso ai dati o per trasferire il traffico dai volumi ad accesso elevato. I volumi della cache sono ideali per carichi di lavoro a elevata intensità di lettura, in particolare quando i client devono accedere ripetutamente agli stessi dati.

Con il caching dei volumi BlueXP, hai a disposizione funzionalità di caching per il cloud, in particolare per Amazon FSX per NetApp ONTAP, Cloud Volumes ONTAP e on-premise come ambienti di lavoro.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Scopri di più sul caching dei volumi BlueXP"].



== Fabbrica dei carichi di lavoro



=== 29 giugno 2025



==== Aggiornamento delle autorizzazioni per i database

La seguente autorizzazione è ora disponibile in modalità _sola lettura_ per i database:  `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]



==== Supporto del servizio di notifica di fabbrica del carico di lavoro BlueXP

Il servizio di notifica di BlueXP Workload Factory consente a Workload Factory di inviare notifiche al servizio di avvisi BlueXP o a un argomento Amazon SNS. Le notifiche inviate agli avvisi BlueXP vengono visualizzate nel pannello degli avvisi BlueXP. Quando la Workload Factory pubblica notifiche su un argomento Amazon SNS, i sottoscrittori dell'argomento (ad esempio persone o altre applicazioni) ricevono le notifiche sugli endpoint configurati per l'argomento (ad esempio, tramite e-mail o SMS).

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurare le notifiche di fabbrica del carico di lavoro BlueXP"]



=== 04 maggio 2025



==== Supporto di completamento automatico di CloudShell

Quando si utilizza la fabbrica CloudShell del carico di lavoro di BlueXP , è possibile iniziare a digitare un comando e premere il tasto Tab per visualizzare le opzioni disponibili. Se esistono più possibilità, l'interfaccia CLI visualizza un elenco di suggerimenti. Questa funzionalità migliora la produttività riducendo al minimo gli errori e accelerando l'esecuzione dei comandi.



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



=== 30 marzo 2025



==== CloudShell riporta risposte di errore generate dall'ai per i comandi CLI di ONTAP

Quando si utilizza CloudShell, ogni volta che si invia un comando CLI di ONTAP e si verifica un errore, è possibile ottenere risposte agli errori generate dall'intelligenza artificiale che includono una descrizione del guasto, la causa del guasto e una risoluzione dettagliata.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilizzare CloudShell"]



==== iam:aggiornamento autorizzazioni SimulatePermissionPolicy

Ora puoi gestire `iam:SimulatePrincipalPolicy` il permesso dalla console workload Factory quando Aggiungi ulteriori credenziali di account AWS o Aggiungi una nuova funzionalità del workload come il workload Genai.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]



=== 02 febbraio 2025



==== CloudShell disponibile nella console di fabbrica del workload BlueXP

CloudShell è disponibile da qualsiasi luogo nella console della workload Factory di BlueXP . CloudShell ti consente di utilizzare le credenziali AWS e ONTAP fornite nel tuo account BlueXP  ed eseguire i comandi dell'interfaccia a riga di comando di AWS o i comandi dell'interfaccia a riga di comando di ONTAP in un ambiente simile alla shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilizzare CloudShell"]



==== Aggiornamento delle autorizzazioni per i database

Il seguente permesso è ora disponibile in modalità _Read_ per i database: `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]
